meta:
  url: https://ahandsel.github.io/Git_GitHub_Intro/
  title: Intro to Git & Github
  description:
  siteName:
  sns: ['github']
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    languages:
      - javascript
      - html
    plugins:
      - line-numbers
    theme: tomorrow
      # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight | default
extends:
  #js: index.js
  css: style.css
  #webpack: webpack.config.js